var settings = {
    START_WINDOW_X: 100,
    START_WINDOW_Y: 100,
    START_WINDOW_WIDTH: 650,
    START_WINDOW_HEIGHT: 450,
    MIN_WINDOW_WIDTH: 200,
    MIN_WINDOW_HEIGHT: 120,
    MAX_WINDOW_COUNT: 50
};